### ISSUE TITLE
.DS_Store

### ISSUE THREAD

**Issue by johnareid54** [GeekyAnts/flutter-starter-kit#19]
In the route folder (as well as in many sub folders) you have a file called **.DS_Store** as these refer to Mac's file folder and has nothing to do with flutter, it might be better to remove such files.  Personally I find these files a right pain in the neck when I transfer files from my MacBook to  Windows.

The following web page describes how you can disabled them on a mac:

https://www.techrepublic.com/article/how-to-disable-the-creation-of-dsstore-files-for-mac-users-folders/

**Comment by HacDan** [comment]
I think in this case a well written .gitignore would be more better fitting for the project.

**Comment by madhav23bansal** [comment]
Rectified.
